[package]
name = "hstry-tui"
version.workspace = true
edition.workspace = true

[dependencies]
hstry-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
clap.workspace = true
crossterm.workspace = true
ratatui.workspace = true
